### ISSUE TITLE
Possibility to get 3 different models?

### ISSUE THREAD

**Issue by richipower** [Jack-CV/PCN-FaceDetection-FaceAlignment#35]
Hello! i am trying to port the implementation to other frameworks, and i was wondering if its possible to split the PCN.caffemodel into three parts, like the .prototxt to have PCN-1.caffemodel, PCN-2.caffemodel, PCN-3.caffemodel ? 

thanks!

**Comment by DecentMakeover** [comment]
Hi i was trying to convert the model to tensorflow, But the issue is that it has 3 prototxt files, is there anything i can do ?
