### ISSUE TITLE
libPCN.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BaofengZan** [Jack-CV/PCN-FaceDetection-FaceAlignment#38]
运行sh run.sh picture/video/fddb报错
./picture/video/picture: error while loading shared libraries: libPCN.so: cannot open shared object file: No such file or directory
我的opencv为3.4 是不是不兼容??

**Comment by Jack-CV** [comment]
Sorry, I haven't compiled this with opencv 3.4. It worked on my computer with opencv 2.4. I don't know if 2.4 is compatible with 3.4

**Comment by lrain-CN** [comment]
> 
> 
> 运行sh run.sh picture/video/fddb报错
> ./picture/video/picture: error while loading shared libraries: libPCN.so: cannot open shared object file: No such file or directory
> 我的opencv为3.4 是不是不兼容??

需要把当前目录加入到环境中export LD_LIBRARY_PATH=./
