### ISSUE TITLE
已经把caffe-master的目录添加进去了，可还是有错误。。

### ISSUE THREAD

**Issue by Andrawzyf** [Jack-CV/PCN-FaceDetection-FaceAlignment#39]
PCN.h:12:27: fatal error: caffe/caffe.hpp: No such file or directory

**Comment by Jack-CV** [comment]
我没有遇到过这个问题，不过我猜测是编译caffe过程不对，或者某些包的版本不对，只能再google下试试了。。。。

**Comment by jiayifang1** [comment]
你好，我这面也出现这样的问题，我还没改任何路径，在目录下执行make时候就出现了如下错误，如您能抽出时间解答以下将十分感谢。

yf@jyf-All-Series:~/JYF/PCN/FaceKit-master/PCN$ make
g++ -shared -fPIC -o libPCN.so PCN.cpp -std=c++11 -DCPU_ONLY  -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_video -lopencv_videoio -lcaffe -lglog -lboost_system -lprotobuf   -O3 
In file included from PCN.cpp:1:0:
PCN.h:13:10: fatal error: caffe/caffe.hpp: 没有那个文件或目录
 #include "caffe/caffe.hpp"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:13: recipe for target 'libPCN.so' failed
make: *** [libPCN.so] Error 1
